export enum EditorActions {
    SAVE = 'EDITOR.SAVE',
    UPDATE = 'EDITOR.UPDATE',
    ADD = 'EDITOR.ADD',
    DELETE = 'EDITOR.DELETE',
    SELECT = 'EDITOR.SELECT',
    UP_ARROW = 'EDITOR.UP_ARROW',
    DOWN_ARROW = 'EDITOR.DOWN_ARROW',
    DRAG_START = 'EDITOR.DRAG_START',
    DRAG_END = 'EDITOR.DRAG_END',
    DRAG_DROP = 'EDITOR.DRAG_DROP',
    LOAD = 'EDITOR.LOAD',
    UPDATE_TITLE = 'EDITOR.UPDATE_TITLE',
}
