export enum SidebarActions {
    ADD = 'SIDEBAR.ADD',
    DELETE = 'SIDEBAR.DELETE',
    OPEN_EDITOR = 'SIDEBAR.OPEN_EDITOR',
    OPEN_FOLDER = 'SIDEBAR.OPEN_FOLDER',
    SET_FILES = 'SIDEBAR.SET_FILES',
    LOAD = 'SIDEBAR.LOAD',
}
